GH-1107: Kafka metrics lag check
spring-cloud/spring-cloud-stream-binder-kafka pull request #1123
Opened 2021-08-18 23:58 UTC by sobychacko

When KafkaBinderMetrics checks lags for offsets in partitions, if the partitions
have nothing committed yet, it unnecessarily tries to find the last committed offset.
This is causing some unncessary logging. Avoid this by only checking the committed
offsets in a partition, if the current end offset is greater than zero.

Resolves https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/issues/1107

2021-08-20 18:55 UTC, garyrussell requested changes
I am not sure what's driving this change; when I tested this, I simply got offset=0 for partitions that had no committed offset.
```java
@KafkaListener(id = "kbgh1123", topics = "kbgh1123")
public void listen(String in, Consumer<?, ?> consumer) {
	Map<TopicPartition, OffsetAndMetadata> committed =
			consumer.committed(Set.of(new TopicPartition("kbgh1123", 0), new TopicPartition("kbgh1123", 1)));
	System.out.println(in + "\n" + committed);
}
```
```
foo
{kbgh1123-1=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}, kbgh1123-0=OffsetAndMetadata{offset=0, leaderEpoch=null, metadata=''}}
```

2021-08-20 18:55 UTC, garyrussell commented on spring-cloud-stream-binder-kafka/src/main/java/org/springframework/cloud/stream/binder/kafka/KafkaBinderMetrics.java
>  				.entrySet()) {
Why not get all the committed offsets in a single call here `.committed(topicPartitions)` rather that one-at-a-time in the loop below?

2021-08-20 19:28 UTC, garyrussell commented
Oh; sorry - I see it's these logs he's complaining about `Found no committed offset for partition kbgh1123-1`.

I still think it would be better to fetch them in one call; why not advise the user the set the log level for `o.a.k.c.c.internals.ConsumerCoordinator` to WARN?

2021-08-20 19:45 UTC, sobychacko commented
@garyrussell Ya, we can certainly advise the user of that. I saw your comment on the issue. I was thinking that if we already know that the end offset for the partition is `0`, then why attempt another `committed(...)` call for finding the current offset? But now I realize that, in between those checks, if the offsets have advanced, then we will miss those updates. Therefore, I could see this PR as moot. We can close this PR and then wait for the user to confirm if the `WARN` approach is all they need. What do you think?

2021-08-23 12:52 UTC, garyrussell commented
Agreed. But I would still prefer to see a single call to `committed()`. It is a blocking call. Perhaps we should open a new issue for that.

2021-08-23 20:11 UTC, sobychacko commented
Closing this PR; The above concern is addressed through https://github.com/spring-cloud/spring-cloud-stream-binder-kafka/pull/1130.

2021-08-23 20:11 UTC, closed without merging